[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

; Hızlandırma ve optimizasyon için
build_flags = -Ofast
              -DPIO_FRAMEWORK_ARDUINO_ENABLE_RTTI ; Gerekiyorsa ekleyin
              
; Kütüphaneleri yönetmek için
lib_deps =
    bolderflight/Bolder Flight Systems SBUS @ ^8.1.0
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BusIO @ ^1.14.5
    adafruit/Adafruit HMC5883 Unified @ ^1.2.3
    adafruit/Adafruit BMP085 Unified @ ^1.1.2


; Temiz ve hızlı derleme için gereksiz paket tanımlarını kaldırdık
[platformio]
src_dir = src