[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower

build_flags = 
    -Ofast
    -DPIO_FRAMEWORK_ARDUINO_ENABLE_RTTI
    -D__FREERTOS=1
    -DFREERTOS_ENABLED
    -DMAVLINK_DIALECT=common
    -I.pio/libdeps/pico/c_library_v2
    -I.pio/libdeps/pico/c_library_v2/common

lib_deps =
    bolderflight/Bolder Flight Systems SBUS @ ^8.1.4
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit BusIO @ ^1.17.4
    adafruit/Adafruit HMC5883 Unified @ ^1.2.3
    adafruit/Adafruit BMP085 Unified @ ^1.1.2
    https://github.com/mavlink/c_library_v2.git

[platformio]
src_dir = src